name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: echo "Build successfully"
    - run: npm run test
    - run: echo "All tests passed succesfully!"
      env:
        CI: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Build Production and Deploy
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install -g surge
      - run: npm install
      - run: npm run generate
      - run: echo "Generated /dist files for production"
      - run: echo "Going to deploy to Surge..."
      - run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      - run: echo "Deployed successfully!"

  notify:
    needs: deploy
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
